import type { ActionRecord, SelectorCandidate } from './collector/actions'
import type { NavigationEntry } from './collector/session'
import type { Marker } from './bundle'
import { REDACTED } from './collector/redact'

/**
 * A Playwright skeleton from the action trail.
 *
 * Deliberately only a skeleton: it reproduces what happened and asserts nothing. The
 * assertions come from the ARIA snapshot each action carries in `actions.json`, which
 * records what the action actually changed — and choosing which of those changes is
 * worth asserting, and what to call the test, is a judgement the generator has no basis
 * for. The header points whoever opens the file at the data needed to make it.
 *
 * Pure: trail in, TypeScript source out.
 */

/** Escape for a single-quoted TypeScript string literal. */
export function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`
}

/**
 * The best locator the candidates support, in the order Playwright itself recommends:
 * a test id if the app has one, otherwise the accessible role and name, and only then
 * anything structural. A CSS path is the last resort because it breaks on any refactor.
 */
export function locatorFor(candidates: readonly SelectorCandidate[]): string {
  const find = <K extends SelectorCandidate['kind']>(
    kind: K
  ): Extract<SelectorCandidate, { kind: K }> | undefined =>
    candidates.find((c) => c.kind === kind) as Extract<SelectorCandidate, { kind: K }> | undefined

  const testid = find('testid')
  if (testid) return `page.getByTestId(${quote(testid.value)})`

  const role = find('role')
  if (role) return `page.getByRole(${quote(role.role)}, { name: ${quote(role.name)} })`

  const label = find('label')
  if (label) return `page.getByLabel(${quote(label.value)})`

  const text = find('text')
  if (text) return `page.getByText(${quote(text.value)})`

  const id = find('id')
  if (id) return `page.locator(${quote(`#${id.value}`)})`

  const css = find('css')
  if (css) return `page.locator(${quote(css.value)})`

  return 'page.locator(/* snapit could not identify this element */)'
}

const clock = (atMs: number): string => {
  const total = Math.max(0, Math.floor(atMs / 1000))
  return `${Math.floor(total / 60)}:${String(total % 60).padStart(2, '0')}`
}

/** One statement for one action, or null when there is nothing runnable to emit. */
function statement(action: ActionRecord, step: number): string[] {
  const target = locatorFor(action.selectors)
  const at = `// step ${step} at ${clock(action.atMs)}`

  if (action.type === 'fill' || action.type === 'change') {
    if (action.value === REDACTED) {
      return [
        at,
        `// snapit did not record this value: the field looked like a credential.`,
        `await ${target}.fill(process.env.TEST_SECRET ?? '')`
      ]
    }
    return [at, `await ${target}.fill(${quote(action.value ?? '')})`]
  }

  if (action.type === 'submit') {
    // The click that submitted the form is already its own step; emitting a second
    // action here would double it.
    return [`${at} — form submitted by the step above`]
  }

  return [at, `await ${target}.click()`]
}

export type SpecInput = {
  actions: readonly ActionRecord[]
  navigations: readonly NavigationEntry[]
  markers: readonly Marker[]
  /** Offsets markers onto the session clock when they came from a recording. */
  recordingOffsetMs?: number
  bundleName: string
}

const HEADER = (bundleName: string): string[] => [
  '/**',
  ' * Generated by snapit from a recorded session. This is a SKELETON: it reproduces what',
  ' * happened and asserts nothing.',
  ' *',
  ` * Everything needed to finish it is in the bundle beside this file (${bundleName}):`,
  ' *',
  ' *  - actions.json   every step, with an `ariaAfter` snapshot of what that step changed.',
  ' *                   The diff between consecutive snapshots is where assertions come from:',
  ' *                   a new role=status node, a value that changed in place, a node that',
  ' *                   disappeared. Assert what the step accomplished, not that it happened.',
  ' *  - network.har    requests each step caused. A 4xx/5xx here is a bug to report, not an',
  ' *                   assertion to write.',
  ' *  - console.json   errors raised during the run.',
  ' *  - meta.json      markers, if the tester flagged moments. They are scenario boundaries',
  ' *                   and say what the tester was trying to do — the best guide to naming.',
  ' *',
  ' * Match the conventions of the repo this lands in: its fixtures, its base URL handling,',
  ' * its selector style. Where a locator below is a CSS path, prefer a better one if the',
  ' * app offers it.',
  ' */',
  ''
]

export function actionsToSpec(input: SpecInput): string {
  const { actions, navigations, markers, bundleName } = input
  const offset = input.recordingOffsetMs ?? 0

  type Event = { atMs: number; lines: string[] }
  const events: Event[] = []

  navigations.forEach((nav) => {
    events.push({ atMs: nav.atMs, lines: [`await page.goto(${quote(nav.url)})`] })
  })

  actions.forEach((action, i) => {
    events.push({ atMs: action.atMs, lines: statement(action, i + 1) })
  })

  // Markers are stamped on the recording's clock; put them back on the session's so
  // they land between the right steps.
  markers.forEach((m) => {
    const at = m.atMs + offset
    events.push({
      atMs: at,
      lines: ['', `// --- marker at ${clock(at)}${m.note ? `: ${m.note}` : ''} ---`]
    })
  })

  const body = events
    .sort((a, b) => a.atMs - b.atMs)
    .flatMap((e) => e.lines)
    .map((line) => (line.length > 0 ? `  ${line}` : line))

  return [
    ...HEADER(bundleName),
    "import { test, expect } from '@playwright/test'",
    '',
    `test(${quote(`recorded session ${bundleName}`)}, async ({ page }) => {`,
    ...body,
    '',
    '  // TODO: assert what this flow was supposed to achieve. See actions.json.',
    '})',
    ''
  ].join('\n')
}
