/**
 * Icon generator (run with the bundled Electron: `npm run icon`).
 *
 * Renders the snapit mark — an "S" lettermark inside a screenshot crop-frame — to PNG
 * via Chromium, then you build the platform icons from the 1024 master:
 *   sips -z N N icon-1024.png ... && iconutil -c icns snapit.iconset
 * Produces, under build/:
 *   icon-1024.png         full-colour app icon (squircle tile)
 *   trayTemplate.png      16px macOS menubar template (black + alpha)
 *   trayTemplate@2x.png   32px
 */
const { app, BrowserWindow } = require('electron')
const { writeFileSync, mkdirSync } = require('fs')
const { join } = require('path')

// Software compositing — the GPU helper crashes capturing a second transparent page.
app.disableHardwareAcceleration()

const OUT = join(__dirname, '..', 'build')
const TRAY_TS = join(__dirname, '..', 'src', 'main', 'trayIcon.ts')

const dataUrl = (buf) => 'data:image/png;base64,' + buf.toString('base64')

// Emit src/main/trayIcon.ts so the embedded base64 is generated, never hand-pasted.
const trayModule = (templateUrl, colourUrl) => `/**
 * Tray icons as embedded data URLs — GENERATED by \`npm run icon\` (do not hand-edit).
 *
 * Embedded rather than read from disk so the tray works in dev, in the built app,
 * and on every OS without an asset-path or packaging dependency.
 *
 * - TEMPLATE: black + alpha; macOS tints it for the menubar (light/dark).
 * - COLOUR: the full squircle mark; self-contained so it stays visible on the
 *   varied Windows/Linux system-tray backgrounds where template tinting doesn't apply.
 */
export const TRAY_TEMPLATE_DATA_URL =
  '${templateUrl}'

export const TRAY_COLOUR_DATA_URL =
  '${colourUrl}'
`

// Four rounded corner brackets forming a crop frame. `c` colours the stroke.
const frame = (c) => `
  <svg width="1024" height="1024" viewBox="0 0 1024 1024" fill="none"
       stroke="${c}" stroke-width="40" stroke-linecap="round" stroke-linejoin="round">
    <path d="M250 360 V250 H360"/>
    <path d="M664 250 H774 V360"/>
    <path d="M774 664 V774 H664"/>
    <path d="M360 774 H250 V664"/>
  </svg>`

// Full-colour app icon: dark squircle tile, white crop frame, red "S".
const colour = `<!doctype html><meta charset="utf-8"><style>
  html,body{margin:0;width:1024px;height:1024px;background:transparent}
  .tile{position:absolute;left:92px;top:92px;width:840px;height:840px;border-radius:230px;
    background:linear-gradient(155deg,#3a3a3c,#161618);
    box-shadow:inset 0 3px 0 rgba(255,255,255,.10), inset 0 -4px 0 rgba(0,0,0,.35)}
  svg,.s{position:absolute;inset:0}
  .s{display:flex;align-items:center;justify-content:center;
     font:800 470px -apple-system,'SF Pro Display',system-ui,sans-serif;color:#ff3b30;
     text-shadow:0 10px 28px rgba(0,0,0,.4)}
</style><div class="tile"></div>${frame('#f5f5f7')}<div class="s">S</div>`

// macOS template (menubar): solid-black mark on transparent, tinted by the OS.
const template = `<!doctype html><meta charset="utf-8"><style>
  html,body{margin:0;width:1024px;height:1024px;background:transparent}
  svg,.s{position:absolute;inset:0}
  .s{display:flex;align-items:center;justify-content:center;
     font:800 520px -apple-system,'SF Pro Display',system-ui,sans-serif;color:#000}
</style>${frame('#000')}<div class="s">S</div>`

const wait = (ms) => new Promise((r) => setTimeout(r, ms))

async function shoot(win, html, name) {
  const htmlPath = join(OUT, `${name}.html`)
  writeFileSync(htmlPath, html)
  await win.loadFile(htmlPath)
  await wait(400) // let fonts settle
  return win.webContents.capturePage()
}

app.whenReady().then(async () => {
  mkdirSync(OUT, { recursive: true })
  const win = new BrowserWindow({
    width: 1024,
    height: 1024,
    show: false,
    transparent: true,
    frame: false,
    backgroundColor: '#00000000',
    webPreferences: { offscreen: false }
  })
  try {
    const main = await shoot(win, colour, 'icon')
    writeFileSync(join(OUT, 'icon-1024.png'), main.toPNG())
    const colour32 = main.resize({ width: 32, height: 32 }).toPNG()
    writeFileSync(join(OUT, 'traySquircle@2x.png'), colour32)

    const tray = await shoot(win, template, 'template')
    const template32 = tray.resize({ width: 32, height: 32 }).toPNG()
    writeFileSync(join(OUT, 'trayTemplate@2x.png'), template32)

    writeFileSync(TRAY_TS, trayModule(dataUrl(template32), dataUrl(colour32)))
    console.log('[icon] wrote build/icon-1024.png, build/tray*.png, src/main/trayIcon.ts')
  } catch (e) {
    console.error('[icon] render failed:', e)
  }
  win.destroy()
  app.quit()
})
